# docker-compose.yml
version: '3'
services:
  db:
    image: postgres:latest
    container_name: mydb
    environment:
      POSTGRES_DB: example_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    depends_on:
      - db
    build: .
    container_name: myapp
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/example_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
volumes:
  pgdata: