spring.application.name=GeolocationService

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5454/GEO_DB}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:superSecPassword}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8081

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=admin
spring.rabbitmq.password=goodPassw
scooter.exchange.name=scooter-exchange
scooter.queue=scooter-updated

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6380}
spring.data.redis.password=${REDIS_PASSWORD:}
spring.data.redis.database=0


geo.key=scooters
