server.address=localhost
server.port=8080

spring.application.name=postboy-module
spring.docker.compose.file=services/notification-service/server/module/postboy-module/compose.yaml
spring.devtools.restart.enabled=false

spring.data.redis.port=6379
spring.data.redis.host=localhost
spring.data.redis.username=${REDIS_USER}
spring.data.redis.password=${REDIS_USER_PASSWORD}

spring.mail.host=smtp.yandex.ru
spring.mail.port=465
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
