server.address=localhost
server.port=8080

spring.application.name=postboy-module
spring.docker.compose.file=services/notification-service/server/module/postboy-module/compose.yaml
spring.devtools.restart.enabled=false

spring.data.redis.port=6379
spring.data.redis.host=localhost
spring.data.redis.username=${REDIS_USER}
spring.data.redis.password=${REDIS_USER_PASSWORD}
