server:
  port: 8082

spring:
  application:
    name: statistics-service
  
  rabbitmq:
    enabled: false
    
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

clickhouse:
  url: jdbc:ch:http://10.3.5.67:9000/statisticsDB
  username: user
  password: "user"
  
app:
  events:
    enabled: false