server.port=8082

spring.datasource.url=jdbc:postgresql://10.3.5.11:5432/testDB
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update


spring.rabbitmq.host=XXXXX
spring.rabbitmq.port=00001
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest